java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz005.txt > results/arenas-jazz/analysis_approximation_arenas-jazz005.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz010.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz010.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz015.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz015.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz020.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz020.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz025.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz025.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz030.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz030.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz035.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz035.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz040.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz040.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz045.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz045.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz050.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz050.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz055.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz055.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz060.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz060.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz065.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz065.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz070.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz070.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz075.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz075.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz080.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz080.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz085.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz085.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz090.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz090.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz095.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz095.txt
java -jar centrality.jar -a results/arenas-jazz/approximation_arenas-jazz100.txt >> results/arenas-jazz/analysis_approximation_arenas-jazz100.txt
