java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid005.txt > results/opsahl-powergrid/analysis_approximation_opsahl-powergrid005.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid010.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid010.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid015.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid015.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid020.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid020.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid025.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid025.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid030.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid030.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid035.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid035.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid040.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid040.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid045.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid045.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid050.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid050.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid055.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid055.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid060.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid060.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid065.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid065.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid070.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid070.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid075.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid075.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid080.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid080.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid085.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid085.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid090.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid090.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid095.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid095.txt
java -jar centrality.jar -a results/opsahl-powergrid/approximation_opsahl-powergrid100.txt >> results/opsahl-powergrid/analysis_approximation_opsahl-powergrid100.txt
