java -jar centrality.jar -a results/dolphins/approximation_dolphins005.txt > results/dolphins/analysis_approximation_dolphins005.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins010.txt >> results/dolphins/analysis_approximation_dolphins010.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins015.txt >> results/dolphins/analysis_approximation_dolphins015.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins020.txt >> results/dolphins/analysis_approximation_dolphins020.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins025.txt >> results/dolphins/analysis_approximation_dolphins025.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins030.txt >> results/dolphins/analysis_approximation_dolphins030.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins035.txt >> results/dolphins/analysis_approximation_dolphins035.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins040.txt >> results/dolphins/analysis_approximation_dolphins040.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins045.txt >> results/dolphins/analysis_approximation_dolphins045.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins050.txt >> results/dolphins/analysis_approximation_dolphins050.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins055.txt >> results/dolphins/analysis_approximation_dolphins055.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins060.txt >> results/dolphins/analysis_approximation_dolphins060.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins065.txt >> results/dolphins/analysis_approximation_dolphins065.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins070.txt >> results/dolphins/analysis_approximation_dolphins070.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins075.txt >> results/dolphins/analysis_approximation_dolphins075.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins080.txt >> results/dolphins/analysis_approximation_dolphins080.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins085.txt >> results/dolphins/analysis_approximation_dolphins085.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins090.txt >> results/dolphins/analysis_approximation_dolphins090.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins095.txt >> results/dolphins/analysis_approximation_dolphins095.txt
java -jar centrality.jar -a results/dolphins/approximation_dolphins100.txt >> results/dolphins/analysis_approximation_dolphins100.txt
