java -jar centrality.jar -a results/arenas-email/approximation_arenas-email005.txt > results/arenas-email/analysis_approximation_arenas-email005.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email010.txt >> results/arenas-email/analysis_approximation_arenas-email010.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email015.txt >> results/arenas-email/analysis_approximation_arenas-email015.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email020.txt >> results/arenas-email/analysis_approximation_arenas-email020.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email025.txt >> results/arenas-email/analysis_approximation_arenas-email025.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email030.txt >> results/arenas-email/analysis_approximation_arenas-email030.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email035.txt >> results/arenas-email/analysis_approximation_arenas-email035.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email040.txt >> results/arenas-email/analysis_approximation_arenas-email040.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email045.txt >> results/arenas-email/analysis_approximation_arenas-email045.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email050.txt >> results/arenas-email/analysis_approximation_arenas-email050.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email055.txt >> results/arenas-email/analysis_approximation_arenas-email055.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email060.txt >> results/arenas-email/analysis_approximation_arenas-email060.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email065.txt >> results/arenas-email/analysis_approximation_arenas-email065.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email070.txt >> results/arenas-email/analysis_approximation_arenas-email070.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email075.txt >> results/arenas-email/analysis_approximation_arenas-email075.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email080.txt >> results/arenas-email/analysis_approximation_arenas-email080.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email085.txt >> results/arenas-email/analysis_approximation_arenas-email085.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email090.txt >> results/arenas-email/analysis_approximation_arenas-email090.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email095.txt >> results/arenas-email/analysis_approximation_arenas-email095.txt
java -jar centrality.jar -a results/arenas-email/approximation_arenas-email100.txt >> results/arenas-email/analysis_approximation_arenas-email100.txt
