java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz005.cfg > results/arenas-jazz/approximation_arenas-jazz005.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz010.cfg > results/arenas-jazz/approximation_arenas-jazz010.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz015.cfg > results/arenas-jazz/approximation_arenas-jazz015.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz020.cfg > results/arenas-jazz/approximation_arenas-jazz020.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz025.cfg > results/arenas-jazz/approximation_arenas-jazz025.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz030.cfg > results/arenas-jazz/approximation_arenas-jazz030.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz035.cfg > results/arenas-jazz/approximation_arenas-jazz035.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz040.cfg > results/arenas-jazz/approximation_arenas-jazz040.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz045.cfg > results/arenas-jazz/approximation_arenas-jazz045.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz050.cfg > results/arenas-jazz/approximation_arenas-jazz050.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz055.cfg > results/arenas-jazz/approximation_arenas-jazz055.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz060.cfg > results/arenas-jazz/approximation_arenas-jazz060.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz065.cfg > results/arenas-jazz/approximation_arenas-jazz065.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz070.cfg > results/arenas-jazz/approximation_arenas-jazz070.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz075.cfg > results/arenas-jazz/approximation_arenas-jazz075.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz080.cfg > results/arenas-jazz/approximation_arenas-jazz080.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz085.cfg > results/arenas-jazz/approximation_arenas-jazz085.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz090.cfg > results/arenas-jazz/approximation_arenas-jazz090.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz095.cfg > results/arenas-jazz/approximation_arenas-jazz095.txt
java -Xmx4g -Xms2g -jar centrality.jar -s experiments/arenas-jazz/approximation_arenas-jazz100.cfg > results/arenas-jazz/approximation_arenas-jazz100.txt
