java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid005.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid005.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid010.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid010.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid015.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid015.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid020.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid020.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid025.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid025.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid030.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid030.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid035.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid035.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid040.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid040.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid045.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid045.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid050.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid050.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid055.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid055.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid060.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid060.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid065.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid065.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid070.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid070.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid075.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid075.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid080.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid080.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid085.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid085.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid090.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid090.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid095.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid095.txt
java -jar centrality.jar -s experiments/opsahl-powergrid/approximation_opsahl-powergrid100.cfg > results/opsahl-powergrid/approximation_opsahl-powergrid100.txt
