java -jar centrality.jar -s experiments/dolphins/approximation_dolphins005.cfg > results/dolphins/approximation_dolphins005.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins010.cfg > results/dolphins/approximation_dolphins010.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins015.cfg > results/dolphins/approximation_dolphins015.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins020.cfg > results/dolphins/approximation_dolphins020.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins025.cfg > results/dolphins/approximation_dolphins025.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins030.cfg > results/dolphins/approximation_dolphins030.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins035.cfg > results/dolphins/approximation_dolphins035.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins040.cfg > results/dolphins/approximation_dolphins040.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins045.cfg > results/dolphins/approximation_dolphins045.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins050.cfg > results/dolphins/approximation_dolphins050.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins055.cfg > results/dolphins/approximation_dolphins055.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins060.cfg > results/dolphins/approximation_dolphins060.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins065.cfg > results/dolphins/approximation_dolphins065.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins070.cfg > results/dolphins/approximation_dolphins070.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins075.cfg > results/dolphins/approximation_dolphins075.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins080.cfg > results/dolphins/approximation_dolphins080.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins085.cfg > results/dolphins/approximation_dolphins085.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins090.cfg > results/dolphins/approximation_dolphins090.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins095.cfg > results/dolphins/approximation_dolphins095.txt
java -jar centrality.jar -s experiments/dolphins/approximation_dolphins100.cfg > results/dolphins/approximation_dolphins100.txt
