java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email005.cfg > results/arenas-email/approximation_arenas-email005.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email010.cfg > results/arenas-email/approximation_arenas-email010.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email015.cfg > results/arenas-email/approximation_arenas-email015.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email020.cfg > results/arenas-email/approximation_arenas-email020.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email025.cfg > results/arenas-email/approximation_arenas-email025.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email030.cfg > results/arenas-email/approximation_arenas-email030.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email035.cfg > results/arenas-email/approximation_arenas-email035.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email040.cfg > results/arenas-email/approximation_arenas-email040.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email045.cfg > results/arenas-email/approximation_arenas-email045.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email050.cfg > results/arenas-email/approximation_arenas-email050.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email055.cfg > results/arenas-email/approximation_arenas-email055.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email060.cfg > results/arenas-email/approximation_arenas-email060.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email065.cfg > results/arenas-email/approximation_arenas-email065.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email070.cfg > results/arenas-email/approximation_arenas-email070.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email075.cfg > results/arenas-email/approximation_arenas-email075.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email080.cfg > results/arenas-email/approximation_arenas-email080.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email085.cfg > results/arenas-email/approximation_arenas-email085.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email090.cfg > results/arenas-email/approximation_arenas-email090.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email095.cfg > results/arenas-email/approximation_arenas-email095.txt
java -Xmx4g -Xms2g -ea -jar centrality.jar -s experiments/arenas-email/approximation_arenas-email100.cfg > results/arenas-email/approximation_arenas-email100.txt
