java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_010.txt >  results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_020.txt >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_030.txt >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_040.txt >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_050.txt >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_060.txt >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_070.txt >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_080.txt >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_090.txt >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_100.txt >> results/email/analysis.txt
