java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_010.txt 10 >  results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_020.txt 10 >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_030.txt 10 >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_040.txt 10 >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_050.txt 10 >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_060.txt 10 >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_070.txt 10 >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_080.txt 10 >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_090.txt 10 >> results/email/analysis.txt
java -jar centrality.jar -a results/email/email_indices.txt results/email/ca_email_100.txt 1 >> results/email/analysis.txt
