java -jar centrality.jar -s exp/email/ca_email_010.cfg > results/email/ca_email_010.txt
java -jar centrality.jar -s exp/email/ca_email_020.cfg > results/email/ca_email_020.txt
java -jar centrality.jar -s exp/email/ca_email_030.cfg > results/email/ca_email_030.txt
java -jar centrality.jar -s exp/email/ca_email_040.cfg > results/email/ca_email_040.txt
java -jar centrality.jar -s exp/email/ca_email_050.cfg > results/email/ca_email_050.txt
java -jar centrality.jar -s exp/email/ca_email_060.cfg > results/email/ca_email_060.txt
java -jar centrality.jar -s exp/email/ca_email_070.cfg > results/email/ca_email_070.txt
java -jar centrality.jar -s exp/email/ca_email_080.cfg > results/email/ca_email_080.txt
java -jar centrality.jar -s exp/email/ca_email_090.cfg > results/email/ca_email_090.txt
java -jar centrality.jar -s exp/email/ca_email_100.cfg > results/email/ca_email_100.txt
